FROM node:18-alpine

WORKDIR /opt/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Build Strapi
RUN npm run build

# Expose port
EXPOSE 1337

# Start Strapi in development mode
CMD ["npm", "run", "develop"]