name: keploy-test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Keploy CLI (Manual & Stable)
        run: |
          mkdir -p $HOME/.keploy/bin
          curl -L https://github.com/keploy/keploy/releases/download/v2.6.14/keploy_linux_amd64.tar.gz -o keploy.tar.gz
          tar -xzf keploy.tar.gz
          mv keploy $HOME/.keploy/bin/keploy
          chmod +x $HOME/.keploy/bin/keploy
          echo "$HOME/.keploy/bin" >> $GITHUB_PATH
          echo "Keploy Installed at:"
          ls -l $HOME/.keploy/bin
          $HOME/.keploy/bin/keploy --version

      - name: Set up JDK 21 with Oracle
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Build Spring Boot Project (Maven)
        run: |
          cd onelinedaily-backend
          mvn clean package

      - name: Start Backend & Run Keploy Tests
        run: |
          export PATH="$HOME/.keploy/bin:$PATH"
          cd onelinedaily-backend
          nohup java -jar target/*.jar &
          sleep 10
          keploy test -c "java -jar target/*.jar"
